### ISSUE TITLE
question about attention unet

### ISSUE THREAD

**Issue by Y-P-W** [bigmb/Unet-Segmentation-Pytorch-Nest-of-Unets#12]
When I chose unet, I got the following error. How can I fix it?
Traceback (most recent call last):
  File "/home/pharos/Pharos/Program/Att_U-Net/Unet-Segmentation-Pytorch-Nest-of-Unets-master/pytorch_run.py", line 100, in <module>
    torchsummary.summary(model_test, input_size=(3, 224, 224))
  File "/home/pharos/anaconda3/lib/python3.7/site-packages/torchsummary/torchsummary.py", line 72, in summary
    model(*x)
  File "/home/pharos/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/pharos/Pharos/Program/Att_U-Net/Unet-Segmentation-Pytorch-Nest-of-Unets-master/Models.py", line 349, in forward
    x4 = self.Att5(g=d5, x=e4)
  File "/home/pharos/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 543, in __call__
    hook_result = hook(self, input, result)
  File "/home/pharos/anaconda3/lib/python3.7/site-packages/torchsummary/torchsummary.py", line 19, in hook
    summary[m_key]["input_shape"] = list(input[0].size())
IndexError: tuple index out of range

**Comment by bigmb** [comment]
It's because of your input size. 
If possible change it to 256X256. Should be divisible by 2, according to the depth of the model.

**Comment by Y-P-W** [comment]
I tried it, but it's still an error. I feel that maybe my data is wrong. Can you describe your data, such as the size and depth of the image of training and labeled data? I'd like to use this project to try the segmentation of arteries and veins.  Can you give me some suggestions on how to modify the program to suit my project，thanks!

**Comment by bigmb** [comment]
So, my data was variable. (it was 3x256x256 , 3x128x128, 3x64x64)
Label data was single channel. depending upon the input i am using. 

is it a binary segmentation or multi segmentation? if it's multi then you need to change it to softmax function.

**Comment by Y-P-W** [comment]
I want to do binary segmentation of blood vessel  first, and do the multi segmentation in the modified model. 
 when i used train image(3*256*256) and label image(1*256*256) in Attention  U-Net, I still have the following error. "IndexError: tuple index out of range"
And  i fixed the second error " RuntimeError" by Normalize the training data without testing data，But I don't quite understand why.
please guide!thanks

**Comment by bigmb** [comment]
In attention unet, can you tell me where the error is?
Is it at x4?
Does it run for other models?

If its binary segmentation  then the code should run perfectly.

**Comment by Y-P-W** [comment]
Errors occur  in the Attention unet and R2AttU_Net. Others U-Net run perfectly after  i fixed the second error " RuntimeError" .

Traceback (most recent call last):
  File "/home/pharos/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3325, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-8921a5de8bc5>", line 1, in <module>
    runfile('/home/pharos/Pharos/Program/Att_U-Net/Unet-Segmentation-Pytorch-Nest-of-Unets-master/pytorch_run.py', wdir='/home/pharos/Pharos/Program/Att_U-Net/Unet-Segmentation-Pytorch-Nest-of-Unets-master')
  File "/home/pharos/Pharos/Download/pycharm-community-anaconda-2019.2.3/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/home/pharos/Pharos/Download/pycharm-community-anaconda-2019.2.3/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/pharos/Pharos/Program/Att_U-Net/Unet-Segmentation-Pytorch-Nest-of-Unets-master/pytorch_run.py", line 100, in <module>
    torchsummary.summary(model_test, input_size=(3, 256, 256))
  File "/home/pharos/anaconda3/lib/python3.7/site-packages/torchsummary/torchsummary.py", line 72, in summary
    model(*x)
  File "/home/pharos/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/pharos/Pharos/Program/Att_U-Net/Unet-Segmentation-Pytorch-Nest-of-Unets-master/Models.py", line 349, in forward
    x4 = self.Att5(g=d5, x=e4)
  File "/home/pharos/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 543, in __call__
    hook_result = hook(self, input, result)
  File "/home/pharos/anaconda3/lib/python3.7/site-packages/torchsummary/torchsummary.py", line 19, in hook
    summary[m_key]["input_shape"] = list(input[0].size())
IndexError: tuple index out of range

please , thanks!

**Comment by bigmb** [comment]
comment torchsummary.
It has this issue. Run without that and let me know if that works.

I have had that problem and I had upgraded pytorch to 1.1.0 and still had this issue.

**Comment by Y-P-W** [comment]
thanks for your replied! It can work without torchsummary.
But as i mentioned above, I had modified data_transform (line 121th) to solve the following problem.
I checked the meaning of mean and std in torchvision.transforms.Normalize, mean: (M1,...,Mn) and std: (S1,..,Sn) for n channels. I think the error is because the normalization cannot be used on the label image[256 x 256].
To solve this problem, i commented "torchvision.transforms.Normalize(mean=[0.5, 0.5, 0.5], std=[0.5, 0.5, 0.5])"(line 125th). 
And i  added two lines of code at line 297th and 298th.
`Norm = torchvision.transforms.Normalize(mean=[0.5, 0.5, 0.5], std=[0.5, 0.5, 0.5]) 
s_tb = Norm(s_tb)`
Do you think it is right? Do i need to normalize the test label image?

Error:
Traceback (most recent call last):
File "/home/pharos/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3325, in run_code
exec(code_obj, self.user_global_ns, self.user_ns)
File "", line 1, in
runfile('/home/pharos/Pharos/Program/Att_U-Net/Unet-Segmentation-Pytorch-Nest-of-Unets-master/pytorch_run.py', wdir='/home/pharos/Pharos/Program/Att_U-Net/Unet-Segmentation-Pytorch-Nest-of-Unets-master')
File "/home/pharos/Pharos/Download/pycharm-community-anaconda-2019.2.3/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
pydev_imports.execfile(filename, global_vars, local_vars) # execute the script
File "/home/pharos/Pharos/Download/pycharm-community-anaconda-2019.2.3/helpers/pydev/pydev_imps/pydev_execfile.py", line 18, in execfile
exec(compile(contents+"\n", file, 'exec'), glob, loc)
File "/home/pharos/Pharos/Program/Att_U-Net/Unet-Segmentation-Pytorch-Nest-of-Unets-master/pytorch_run.py", line 295, in
s_label = data_transform(im_label)
File "/home/pharos/anaconda3/lib/python3.7/site-packages/torchvision/transforms/transforms.py", line 61, in call
img = t(img)
File "/home/pharos/anaconda3/lib/python3.7/site-packages/torchvision/transforms/transforms.py", line 166, in call
return F.normalize(tensor, self.mean, self.std, self.inplace)
File "/home/pharos/anaconda3/lib/python3.7/site-packages/torchvision/transforms/functional.py", line 217, in normalize
tensor.sub(mean[:, None, None]).div(std[:, None, None])
RuntimeError: output with shape [1, 256, 256] doesn't match the broadcast shape [3, 256, 256]

**Comment by bigmb** [comment]
if you normalize the test dataset it should be single-channel (it is grayscale right?)
torchvision.transforms.Normalize(mean=[0.5], std=[0.5])
try this.

**Comment by Y-P-W** [comment]
ok, but I have some question. Can you explain the meaning of output channel to me? it is the number of class? why its value is 1 in binary segmentation? If my class (including background) are 3, what is its value? 
if i change sigmoid to softmax,  do the sigmoid in the attention block need to be modified?
thanks!

**Comment by bigmb** [comment]
Out channel - Classes.
if you have 3 classes then it will be 3.

In binary it is 1 , because it just has to find one class and make the rest of the pixels blank. You can make it 2 , but then you have to edit it in how the values will be classified. Just to avoid that classification we keep it 1.

For attention block, it will be focused on one class only. If you want multi attention then I suggest you look into this paper. (https://arxiv.org/pdf/1806.05372.pdf)
If you change it to softmax it will give an error i think becz the output to the next layer will be wrong.
