### ISSUE TITLE
BrokenPipeError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by FreakChan** [bigmb/Unet-Segmentation-Pytorch-Nest-of-Unets#17]
excellent work！
but i got this error during training.
environment:
win7
cuda:10.0
pytorch:1.1.0
Traceback (most recent call last):
  File "<string>", line 1, in <module>
Traceback (most recent call last):
  File "F:/chenzihao/Unet-Segmentation-Pytorch-Nest-of-Unets/pytorch_run.py", line 244, in <module>
  File "F:\chenzihao\miniconda\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "F:\chenzihao\miniconda\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "F:\chenzihao\miniconda\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "F:\chenzihao\miniconda\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    for x, y in train_loader:
  File "F:\chenzihao\miniconda\lib\site-packages\torch\utils\data\dataloader.py", line 278, in __iter__
    run_name="__mp_main__")
  File "F:\chenzihao\miniconda\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "F:\chenzihao\miniconda\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "F:\chenzihao\miniconda\lib\runpy.py", line 85, in _run_code
        exec(code, run_globals)return _MultiProcessingDataLoaderIter(self)
  File "F:\chenzihao\Unet-Segmentation-Pytorch-Nest-of-Unets\pytorch_run.py", line 244, in <module>

  File "F:\chenzihao\miniconda\lib\site-packages\torch\utils\data\dataloader.py", line 682, in __init__
    for x, y in train_loader:
  File "F:\chenzihao\miniconda\lib\site-packages\torch\utils\data\dataloader.py", line 278, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "F:\chenzihao\miniconda\lib\site-packages\torch\utils\data\dataloader.py", line 682, in __init__
    w.start()
  File "F:\chenzihao\miniconda\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "F:\chenzihao\miniconda\lib\multiprocessing\context.py", line 223, in _Popen
    w.start()
  File "F:\chenzihao\miniconda\lib\multiprocessing\process.py", line 112, in start
    return _default_context.get_context().Process._Popen(process_obj)
  File "F:\chenzihao\miniconda\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "F:\chenzihao\miniconda\lib\multiprocessing\popen_spawn_win32.py", line 46, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "F:\chenzihao\miniconda\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    self._popen = self._Popen(self)
  File "F:\chenzihao\miniconda\lib\multiprocessing\context.py", line 223, in _Popen
    _check_not_importing_main()
  File "F:\chenzihao\miniconda\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
    return _default_context.get_context().Process._Popen(process_obj)
  File "F:\chenzihao\miniconda\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "F:\chenzihao\miniconda\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)
  File "F:\chenzihao\miniconda\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
BrokenPipeError: [Errno 32] Broken pipe

**Comment by FreakChan** [comment]
when i seted the num_workers=0, it worked. but i dont kown why

**Comment by bigmb** [comment]
Num_workers basically is for parrelal processing of threads. 
I think in your case 2 threads are conflicting, so before the first thread is finished,  it starts the second one and it gives the error. 

But I will still look into it.

**Comment by FreakChan** [comment]
OK. Thanks fo reply!
