### ISSUE TITLE
RuntimeError: output with shape [1, 96, 96] doesn't match the broadcast shape [3, 96, 96]

### ISSUE THREAD

**Issue by EthanYoon** [bigmb/Unet-Segmentation-Pytorch-Nest-of-Unets#21]

**Comment by EthanYoon** [comment]
Hi,when I run your code,I come across this error.
the full infomations belows:
Successfully created the main directory './model' 
Successfully created the prediction directory './model/pred' of dice loss
Successfully created the model directory './model/Unet_D_15_4' 
/home/hfcui/.local/lib/python3.6/site-packages/torch/optim/lr_scheduler.py:100: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule.See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  "https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate", UserWarning)
Traceback (most recent call last):
  File "pytorch_run.py", line 265, in <module>
    for x, y in train_loader:
  File "/home/hfcui/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/home/hfcui/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/home/hfcui/.local/lib/python3.6/site-packages/torch/_utils.py", line 385, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/hfcui/.local/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/hfcui/.local/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/hfcui/.local/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/media/nomachine/project/Unet-Segmentation-Pytorch-Nest-of-Unets/Data_Loader.py", line 96, in __getitem__
    return self.tx(i1), self.lx(l1)
  File "/home/hfcui/.local/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 70, in __call__
    img = t(img)
  File "/home/hfcui/.local/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 175, in __call__
    return F.normalize(tensor, self.mean, self.std, self.inplace)
  File "/home/hfcui/.local/lib/python3.6/site-packages/torchvision/transforms/functional.py", line 217, in normalize
    tensor.sub_(mean[:, None, None]).div_(std[:, None, None])
RuntimeError: output with shape [1, 96, 96] doesn't match the broadcast shape [3, 96, 96]

**Comment by bigmb** [comment]
Which line is giving this issue?

**Comment by bigmb** [comment]
What is the shape of your input data and label?

**Comment by EthanYoon** [comment]
> Which line is giving this issue?

File "pytorch_run.py", line 265, in
for x, y in train_loader:
(I noted some codes.)

**Comment by EthanYoon** [comment]
> What is the shape of your input data and label?

I used "2d_from_3d.py" to deal with data.
the data source is ADNI_002_S_0295_MR_HarP_135_final_release_2015.
I am a beginner,So I am still learning CV.the words I express may not professional.sry.

**Comment by EthanYoon** [comment]
> What is the shape of your input data and label?

(1, 128, 128)？ I think it is.
cuz I use the grey jpg.I noticed that you use
torchvision.transforms.Normalize(mean=(0.5, 0.5, 0.5), std=(0.5, 0.5, 0.5)
to Normalize grey jpg.
I wonder if my pytorch version is so high? my pytorch version is 1.3.1

**Comment by bigmb** [comment]
The input image must be 3 channel and the label must be single channel. 
Here the normalization occurs for all the 3 channels of your input image  , so if you provide a single channel image ( grey scale) then it will show an error.
