### ISSUE TITLE
torchsummary.summary attention unet

### ISSUE THREAD

**Issue by Rainfor1** [bigmb/Unet-Segmentation-Pytorch-Nest-of-Unets#22]
HI!
very nice work!

when I use the attention unet, torchsummary.summary(model_test, input_size=(3, 128, 128)) can get the error:

Traceback (most recent call last):
  File "pytorch_run.py", line 122, in <module>
    torchsummary.summary(model_test, input_size=(3, 128, 128))
  File "/home/lix/miniconda3/envs/ptseg/lib/python3.6/site-packages/torchsummary/torchsummary.py", line 74, in summary
    model(*x)
  File "/home/lix/miniconda3/envs/ptseg/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lix/Documents/code/Unet-Segmentation-Pytorch-Nest-of-Unets/Models.py", line 360, in forward
    x4 = self.Att5(g=d5, x=e4)
  File "/home/lix/miniconda3/envs/ptseg/lib/python3.6/site-packages/torch/nn/modules/module.py", line 495, in __call__
    hook_result = hook(self, input, result)
  File "/home/lix/miniconda3/envs/ptseg/lib/python3.6/site-packages/torchsummary/torchsummary.py", line 20, in hook
    summary[m_key]["input_shape"] = list(input[0].size())
IndexError: tuple index out of range

Could you please give me a solution? I'll very appreciate about it!

**Comment by bigmb** [comment]
Hey.
Torch summary for attention unet and r2attention unet doesn't work.
Check out line 89, so if you are using any of those 2 then comment out that torch summary.
