### ISSUE TITLE
Help for data or data format

### ISSUE THREAD

**Issue by ALEXdwt** [bigmb/Unet-Segmentation-Pytorch-Nest-of-Unets#57]
Thanks for your work!

A dataset by myself was used to test your code, but it comes:
Traceback (most recent call last):
  File "E:\dwt\BrainExtract\PythonUnet\Unet-Segmentation-Pytorch-Nest-of-Unets-master\pytorch_run.py", line 251, in <module>
    for x, y in train_loader:
  File "F:\pythontool\lib\site-packages\torch\utils\data\dataloader.py", line 628, in __next__
    data = self._next_data()
  File "F:\pythontool\lib\site-packages\torch\utils\data\dataloader.py", line 671, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "F:\pythontool\lib\site-packages\torch\utils\data\_utils\fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "F:\pythontool\lib\site-packages\torch\utils\data\_utils\fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "E:\dwt\BrainExtract\PythonUnet\Unet-Segmentation-Pytorch-Nest-of-Unets-master\Data_Loader.py", line 104, in __getitem__
    img = self.tx(i1)
  File "F:\pythontool\lib\site-packages\torchvision\transforms\transforms.py", line 95, in __call__
    img = t(img)
  File "F:\pythontool\lib\site-packages\torch\nn\modules\module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "F:\pythontool\lib\site-packages\torchvision\transforms\transforms.py", line 270, in forward
    return F.normalize(tensor, self.mean, self.std, self.inplace)
  File "F:\pythontool\lib\site-packages\torchvision\transforms\functional.py", line 360, in normalize
    return F_t.normalize(tensor, mean=mean, std=std, inplace=inplace)
  File "F:\pythontool\lib\site-packages\torchvision\transforms\functional_tensor.py", line 940, in normalize
    return tensor.sub_(mean).div_(std)
RuntimeError: output with shape [1, 96, 96] doesn't match the broadcast shape [3, 96, 96]

I cut the 3D MRI data into 2D images (size 256*256), and save them as png format, then put some of the pngs into the data folder separately,  is there any problem?

**Comment by bigmb** [comment]
Input to the model in pytorch run is of shape 3 and not 1.
So you can either change the shape of the model input in pytorch_run or make your image into 3 channel.
