### ISSUE TITLE
IndexError: tuple index out of range

### ISSUE THREAD

**Issue by Kaihua1203** [bigmb/Unet-Segmentation-Pytorch-Nest-of-Unets#60]
Hi,first of all,thanks for your great jod!
Secondly,when i used R2AttU_Net, i met the indexError: tuple index out of range. The exact error is as following. How can i fix it correctly?
Traceback (most recent call last):
  File "C:\Users\17389\Desktop\Unet-Segmentation-Pytorch-Nest-of-Unets-master\pytorch_run2.py", line 109, in <module>
    torchsummary.summary(model_test, input_size=(3, 128, 128))
  File "D:\Anaconda\envs\pytorch\lib\site-packages\torchsummary\torchsummary.py", line 72, in summary
    model(*x)
  File "D:\Anaconda\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\17389\Desktop\Unet-Segmentation-Pytorch-Nest-of-Unets-master\Models.py", line 439, in forward
    e4 = self.Att5(g=d5, x=e4)
  File "D:\Anaconda\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 1547, in _call_impl
    hook_result = hook(self, args, result)
  File "D:\Anaconda\envs\pytorch\lib\site-packages\torchsummary\torchsummary.py", line 19, in hook
    summary[m_key]["input_shape"] = list(input[0].size())
IndexError: tuple index out of range

i'm appreciate it if u can reply me!

**Comment by Kaihua1203** [comment]
In R2attention unet, the error is  at e4.

**Comment by bigmb** [comment]
Increase the input size. 
#12

**Comment by bigmb** [comment]
Please reopen if that doesn't solve the issue.
